### ISSUE TITLE
Question: allowLists: true but match list item

### ISSUE THREAD

**Issue by Mister-Hope** [textlint-rule/textlint-rule-en-capitalization#8]
![image](https://user-images.githubusercontent.com/33315834/96370656-2d210180-1191-11eb-8aeb-2ea3a8aabe06.png)

Heres the docs

And here is my config:

```yml
rules:
  "@textlint-rule/no-unmatched-pair": true

  apostrophe: true

  common-misspellings: true

  diacritics: true

  en-capitalization:
    allowHeading: false
    allowLists: true

  # stop-words:
  #   severity: warning

  # terminology:
  #   terms:
  #     - Stylus
  #     - VuePress
  #     - - front[- ]matter
  #       - frontmatter
  #   exclude:
  #     - node
  #     - repo

  # write-good:
  #   severity: warning

  zh-half-and-full-width-bracket:
    bracket: halfWidth

filters:
  comments: true
```

Then why is the plugin still correcting this:
![image](https://user-images.githubusercontent.com/33315834/96370737-78d3ab00-1191-11eb-9b11-26fbf4c27358.png)

**Comment by azu** [comment]
Fmm. `allowLists` aim to ignore list item text.

Its may be a bug.

https://github.com/textlint-rule/textlint-rule-en-capitalization/blob/d4c21faf55334e19ab448b4f84a14aa2d58ab209/src/textlint-rule-en-capitalization.js#L149

**Comment by Mister-Hope** [comment]
It seems that the logic is reversed

```yml
  en-capitalization:
    allowHeading: false
    allowLists: false
```

This will allow lowercase letter in heading and lists.

Besides, why there is allowList**s**, allowFigure**s**, allowWord**s** while allowHeading? It's strange.
